name: Deploy to NAS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy
        run: |
          cd ~/docker-apps/dada-moura-portfolio
          git reset --hard HEAD
          git pull origin main
          sudo docker compose up -d --build
          sleep 3
          sudo docker compose exec -T app python seed/seed_data.py || true
          sudo docker compose exec -T app python init_db.py || true
          sudo docker image prune -f
